// src/lib/weddingDefaults.js
// Default seed data for new wedding plans

export const DEFAULT_CHECKLIST = [
  // 12 months
  { phase: '12_months', task: 'Choose wedding motto', sort_order: 1 },
  { phase: '12_months', task: 'Engagement party planning', sort_order: 2 },
  { phase: '12_months', task: 'Establish a budget', sort_order: 3 },
  { phase: '12_months', task: 'First pass at guest list', sort_order: 4 },
  { phase: '12_months', task: 'Choose a time of year', sort_order: 5 },
  { phase: '12_months', task: 'Choose a date', sort_order: 6 },
  { phase: '12_months', task: 'Choose a vibe / aesthetic', sort_order: 7 },
  { phase: '12_months', task: 'Choose a venue', sort_order: 8 },
  { phase: '12_months', task: 'Choose a caterer', sort_order: 9 },
  { phase: '12_months', task: 'Insure the engagement ring', sort_order: 10 },

  // 11-10 months
  { phase: '11_10_months', task: 'Finalize design vision', sort_order: 1 },
  { phase: '11_10_months', task: 'Book DJ', sort_order: 2 },
  { phase: '11_10_months', task: 'Book photographer', sort_order: 3 },
  { phase: '11_10_months', task: 'Book band', sort_order: 4 },
  { phase: '11_10_months', task: 'Book videographer', sort_order: 5 },
  { phase: '11_10_months', task: 'Book florist', sort_order: 6 },
  { phase: '11_10_months', task: 'Book caterer / bartenders', sort_order: 7 },
  { phase: '11_10_months', task: 'Interview coordinators', sort_order: 8 },
  { phase: '11_10_months', task: 'Begin collecting addresses', sort_order: 9 },
  { phase: '11_10_months', task: 'Set up hotel room block', sort_order: 10 },
  { phase: '11_10_months', task: 'Dress shopping', sort_order: 11 },
  { phase: '11_10_months', task: 'Take engagement photos', sort_order: 12 },

  // 9-8 months
  { phase: '9_8_months', task: 'Buy wedding dress', sort_order: 1 },
  { phase: '9_8_months', task: 'Schedule alterations', sort_order: 2 },
  { phase: '9_8_months', task: 'Send save the dates', sort_order: 3 },
  { phase: '9_8_months', task: 'Book / confirm officiant', sort_order: 4 },
  { phase: '9_8_months', task: 'Schedule hair & makeup trials', sort_order: 5 },
  { phase: '9_8_months', task: 'Create registry', sort_order: 6 },
  { phase: '9_8_months', task: 'Begin selecting wedding party outfits', sort_order: 7 },
  { phase: '9_8_months', task: 'Book rehearsal dinner space', sort_order: 8 },
  { phase: '9_8_months', task: 'Hire ceremony musicians', sort_order: 9 },

  // 6-5 months
  { phase: '6_5_months', task: 'Schedule time together (not planning)', sort_order: 1 },
  { phase: '6_5_months', task: 'Finalize decor plan', sort_order: 2 },
  { phase: '6_5_months', task: 'Finalize lighting plan', sort_order: 3 },
  { phase: '6_5_months', task: 'Begin premarital counseling', sort_order: 4 },
  { phase: '6_5_months', task: 'Make DIY plan', sort_order: 5 },
  { phase: '6_5_months', task: 'Take dance lessons', sort_order: 6 },
  { phase: '6_5_months', task: 'Book transportation for guests', sort_order: 7 },
  { phase: '6_5_months', task: 'Book honeymoon', sort_order: 8 },

  // 3-2 months
  { phase: '3_2_months', task: 'Plan food options', sort_order: 1 },
  { phase: '3_2_months', task: 'Begin drafting vows', sort_order: 2 },
  { phase: '3_2_months', task: 'Select readings', sort_order: 3 },
  { phase: '3_2_months', task: 'Send out invites', sort_order: 4 },
  { phase: '3_2_months', task: 'Create rain / crisis plan', sort_order: 5 },
  { phase: '3_2_months', task: 'Get crafty (DIY items)', sort_order: 6 },
  { phase: '3_2_months', task: 'Shot list with photographer', sort_order: 7 },
  { phase: '3_2_months', task: 'Finalize day-of schedule', sort_order: 8 },
  { phase: '3_2_months', task: 'Marriage license (per state guidelines)', sort_order: 9 },
  { phase: '3_2_months', task: 'Wedding party gifts', sort_order: 10 },
  { phase: '3_2_months', task: 'Bridal shower / bachelorette', sort_order: 11 },
  { phase: '3_2_months', task: 'RSVP deadline — 6 weeks before', sort_order: 12 },
  { phase: '3_2_months', task: 'Select wedding undies', sort_order: 13 },

  // Month of
  { phase: 'month_of', task: 'Pay vendors in full', sort_order: 1 },
  { phase: 'month_of', task: 'Create seating chart and signage', sort_order: 2 },
  { phase: 'month_of', task: 'Create escort cards', sort_order: 3 },
  { phase: 'month_of', task: 'Final venue walkthrough', sort_order: 4 },
  { phase: 'month_of', task: 'Put together vendor tips', sort_order: 5 },
  { phase: 'month_of', task: 'Chase down remaining RSVPs', sort_order: 6 },
  { phase: 'month_of', task: 'Get final numbers to vendors', sort_order: 7 },
  { phase: 'month_of', task: 'Collect memorial table photos', sort_order: 8 },
  { phase: 'month_of', task: 'Make playlists (getting ready, transport, cocktail, reception)', sort_order: 9 },
  { phase: 'month_of', task: 'Finalize ceremony with officiant', sort_order: 10 },
  { phase: 'month_of', task: 'Amazon last-minute purchases', sort_order: 11 },
  { phase: 'month_of', task: 'Confirm all vendor arrival times', sort_order: 12 },

  // Week of
  { phase: 'week_of', task: 'Nail appointment', sort_order: 1 },
  { phase: 'week_of', task: 'Rest and self-care (R&R)', sort_order: 2 },
  { phase: 'week_of', task: 'Dress fitting', sort_order: 3 },
  { phase: 'week_of', task: 'Pack for honeymoon', sort_order: 4 },
  { phase: 'week_of', task: 'Ring cleaning', sort_order: 5 },
  { phase: 'week_of', task: 'Practice vows', sort_order: 6 },
  { phase: 'week_of', task: 'Write notes to each other', sort_order: 7 },
  { phase: 'week_of', task: 'Assemble bathroom baskets and finalize decor', sort_order: 8 },
  { phase: 'week_of', task: 'Break in wedding shoes', sort_order: 9 },
];

export const DEFAULT_BUDGET_CATEGORIES = [
  { category: 'paper_signage',        label: 'Paper & Signage',         default_pct: 0.03 },
  { category: 'venue_ceremony',       label: 'Venue & Ceremony',        default_pct: 0.15 },
  { category: 'food_service',         label: 'Food / Service',          default_pct: 0.18 },
  { category: 'beverage',             label: 'Beverage',                default_pct: 0.10 },
  { category: 'photography',          label: 'Photography / Video',     default_pct: 0.10 },
  { category: 'music_entertainment',  label: 'Music / Entertainment',   default_pct: 0.08 },
  { category: 'florals_decor',        label: 'Florals & Decor',         default_pct: 0.08 },
  { category: 'attire',               label: 'Attire',                  default_pct: 0.08 },
  { category: 'transportation',       label: 'Transportation',          default_pct: 0.05 },
  { category: 'honeymoon',            label: 'Honeymoon',               default_pct: 0.08 },
  { category: 'other',                label: 'Other',                   default_pct: 0.07 },
];

export const DEFAULT_BUDGET_ITEMS = [
  { category: 'paper_signage', item_name: 'Invitations', sort_order: 1 },
  { category: 'paper_signage', item_name: 'Save the Dates', sort_order: 2 },
  { category: 'paper_signage', item_name: 'Escort Cards', sort_order: 3 },
  { category: 'paper_signage', item_name: 'Thank You Cards', sort_order: 4 },
  { category: 'paper_signage', item_name: 'Postage', sort_order: 5 },
  { category: 'paper_signage', item_name: 'Signage', sort_order: 6 },
  { category: 'venue_ceremony', item_name: 'Venue rental fee', sort_order: 1 },
  { category: 'venue_ceremony', item_name: 'Ceremony fees', sort_order: 2 },
  { category: 'venue_ceremony', item_name: 'Setup / breakdown fees', sort_order: 3 },
  { category: 'food_service', item_name: 'Caterer', sort_order: 1 },
  { category: 'food_service', item_name: 'Cake / Dessert table', sort_order: 2 },
  { category: 'food_service', item_name: 'Late night snacks', sort_order: 3 },
  { category: 'beverage', item_name: 'Bar service', sort_order: 1 },
  { category: 'beverage', item_name: 'Toast / champagne', sort_order: 2 },
  { category: 'photography', item_name: 'Photographer', sort_order: 1 },
  { category: 'photography', item_name: 'Videographer', sort_order: 2 },
  { category: 'photography', item_name: 'Photo booth / props', sort_order: 3 },
  { category: 'photography', item_name: 'Wedding album', sort_order: 4 },
  { category: 'music_entertainment', item_name: 'Band / DJ', sort_order: 1 },
  { category: 'music_entertainment', item_name: 'Ceremony musicians', sort_order: 2 },
  { category: 'florals_decor', item_name: 'Bridal bouquet', sort_order: 1 },
  { category: 'florals_decor', item_name: 'Ceremony florals', sort_order: 2 },
  { category: 'florals_decor', item_name: 'Reception centerpieces', sort_order: 3 },
  { category: 'florals_decor', item_name: 'Boutonnières', sort_order: 4 },
  { category: 'florals_decor', item_name: 'Uplighting', sort_order: 5 },
  { category: 'attire', item_name: 'Wedding dress / alterations', sort_order: 1 },
  { category: 'attire', item_name: 'Groom / partner attire', sort_order: 2 },
  { category: 'attire', item_name: 'Bridesmaid dresses', sort_order: 3 },
  { category: 'attire', item_name: 'Groomsmen attire', sort_order: 4 },
  { category: 'attire', item_name: 'Wedding bands', sort_order: 5 },
  { category: 'transportation', item_name: 'Guest transportation / shuttles', sort_order: 1 },
  { category: 'transportation', item_name: 'Bride & Groom getaway car', sort_order: 2 },
];

export const DEFAULT_RUN_OF_SHOW = [
  { phase: 'morning', action: 'Getting ready — Partner 1', sort_order: 1 },
  { phase: 'morning', action: 'Getting ready — Partner 2', sort_order: 2 },
  { phase: 'morning', action: 'Photographer arrives', sort_order: 3 },
  { phase: 'morning', action: 'Hair & makeup finalizes', sort_order: 4 },
  { phase: 'morning', action: 'Wedding party photos', sort_order: 5 },
  { phase: 'morning', action: 'Guests begin arriving', sort_order: 6 },
  { phase: 'morning', action: 'Guests seated', sort_order: 7 },
  { phase: 'ceremony', action: 'Processions', sort_order: 1 },
  { phase: 'ceremony', action: 'Ceremony begins', sort_order: 2 },
  { phase: 'ceremony', action: 'Ceremony ends', sort_order: 3 },
  { phase: 'ceremony', action: 'Recessional', sort_order: 4 },
  { phase: 'cocktail', action: 'Cocktail hour begins', sort_order: 1 },
  { phase: 'cocktail', action: 'Couple portraits', sort_order: 2 },
  { phase: 'cocktail', action: 'Transition to reception', sort_order: 3 },
  { phase: 'reception', action: 'Grand entrance', sort_order: 1 },
  { phase: 'reception', action: 'First dance', sort_order: 2 },
  { phase: 'reception', action: 'Dinner service begins', sort_order: 3 },
  { phase: 'reception', action: 'Toasts', sort_order: 4 },
  { phase: 'reception', action: 'Dancing opens', sort_order: 5 },
  { phase: 'reception', action: 'Cake cutting', sort_order: 6 },
  { phase: 'reception', action: 'Bouquet toss', sort_order: 7 },
  { phase: 'end_of_night', action: 'Last call', sort_order: 1 },
  { phase: 'end_of_night', action: 'Final song', sort_order: 2 },
  { phase: 'end_of_night', action: 'Transportation departs', sort_order: 3 },
  { phase: 'end_of_night', action: 'After party (if applicable)', sort_order: 4 },
];

export const DEFAULT_MUSIC_MOMENTS = [
  { type: 'special_moment', moment_key: 'processional',        song_title: '', artist: '' },
  { type: 'special_moment', moment_key: 'bridal_processional', song_title: '', artist: '' },
  { type: 'special_moment', moment_key: 'recessional',         song_title: '', artist: '' },
  { type: 'special_moment', moment_key: 'entrance',            song_title: '', artist: '' },
  { type: 'special_moment', moment_key: 'first_dance',         song_title: '', artist: '' },
  { type: 'special_moment', moment_key: 'father_daughter',     song_title: '', artist: '' },
  { type: 'special_moment', moment_key: 'mother_son',          song_title: '', artist: '' },
  { type: 'special_moment', moment_key: 'party_starter',       song_title: '', artist: '' },
  { type: 'special_moment', moment_key: 'bouquet_toss',        song_title: '', artist: '' },
  { type: 'special_moment', moment_key: 'cake_cutting',        song_title: '', artist: '' },
  { type: 'special_moment', moment_key: 'last_song',           song_title: '', artist: '' },
];

export const DEFAULT_LEGAL_PRE_WEDDING = [
  { phase: 'pre_wedding', task: 'Apply for marriage license', type: 'Wedding', location: 'Local courthouse', cost: '$50–$100', notes: 'Do 30-60 days before, check expiration window', sort_order: 1 },
  { phase: 'pre_wedding', task: 'Prenuptial agreement (if applicable)', type: 'Legal', location: 'Attorney', cost: 'Varies', sort_order: 2 },
  { phase: 'pre_wedding', task: 'Update beneficiary designations', type: 'Financial', location: 'Employer / Insurance', cost: 'Free', sort_order: 3 },
  { phase: 'pre_wedding', task: 'Review joint insurance needs', type: 'Financial', location: 'Insurance provider', cost: 'Varies', sort_order: 4 },
  { phase: 'pre_wedding', task: 'Insure engagement ring', type: 'Insurance', location: 'Jewelry insurer', cost: '~$300/yr', sort_order: 5 },
];

export const DEFAULT_LEGAL_NAME_CHANGE = [
  { phase: 'name_change', task: 'Social Security card', type: 'Government', location: 'ssa.gov', cost: 'Free', notes: 'Do this FIRST — required for all others', sort_order: 1 },
  { phase: 'name_change', task: "Driver's license / State ID", type: 'Government', location: 'DMV', cost: '$10–30', notes: 'Bring SS card + certified marriage certificate', sort_order: 2 },
  { phase: 'name_change', task: 'Passport', type: 'Government', location: 'travel.state.gov', cost: '$130+', notes: '6–8 week processing, expedite for $60 more', sort_order: 3 },
  { phase: 'name_change', task: 'Bank accounts', type: 'Financial', location: 'Your bank branch', cost: 'Free', sort_order: 4 },
  { phase: 'name_change', task: 'Credit cards', type: 'Financial', location: 'Call each card', cost: 'Free', sort_order: 5 },
  { phase: 'name_change', task: 'Employer / payroll / HR', type: 'Work', location: 'HR department', cost: 'Free', sort_order: 6 },
  { phase: 'name_change', task: 'Voter registration', type: 'Government', location: 'vote.gov', cost: 'Free', sort_order: 7 },
  { phase: 'name_change', task: 'Insurance policies (auto, health, life)', type: 'Insurance', location: 'Your agent', cost: 'Free', sort_order: 8 },
  { phase: 'name_change', task: 'Utilities', type: 'Utilities', location: 'Call each provider', cost: 'Free', sort_order: 9 },
  { phase: 'name_change', task: 'Post office / USPS mail forwarding', type: 'Mail', location: 'usps.com', cost: 'Free', sort_order: 10 },
  { phase: 'name_change', task: 'Update will / estate documents', type: 'Legal', location: 'Attorney', cost: 'Varies', sort_order: 11 },
];
